# helm-chart/templates/service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitor
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
  - port: http
    path: /metrics