name: DevOps Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t myapp:${{ github.sha }} .

    - name: Run tests
      run: |
        docker run myapp:${{ github.sha }} python -c "import flask; print('Flask version:', flask.__version__)"

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: build-test
    environment: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2
      with:
        minikube version: 'v1.31.2'
        driver: docker

    - name: Start Minikube
      run: |
        minikube start
        minikube addons enable ingress

    - name: Build in Minikube environment
      run: |
        eval $(minikube docker-env)
        docker build -t myapp:${{ github.sha }} .

    - name: Deploy with Helm
      run: |
        helm upgrade --install myapp-release ./helm-chart \
          --set image.tag=${{ github.sha }} \
          --set replicaCount=2